import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComp from "../components/Navbar";
import FooterComp from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Physio",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NavbarComp />
				{children}
				<FooterComp />
			</body>
		</html>
	);
}
